leopard_pont_des_arts_prompt: |
  Given:
  - **Leopard's Speed**: 58 km/h
  - **Pont des Arts Bridge Length**: 155 meters

  ### Task:
  Compute the time in **seconds** for a leopard running at full speed to cross the Pont des Arts bridge.

  Use the formula:
  Time (seconds) = Distance (meters) / Speed (m/s)

  Return response in **JSON format**:

  ```json
  {
      "time_seconds": <numeric_value>,
      "explanation": "<brief explanation>"
  }
